feat: Switch to Rust Edition 2024
This also requires adjusting the ELF-.note-defining macros to prevent errors like the following:

```
error: unsafe attribute used without unsafe
  --> src/lib.rs:95:1
   |
95 | uhyve_interface::define_uhyve_interface_version!();
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ usage of unsafe attribute
   |
   = note: this error originates in the macro `uhyve_interface::define_uhyve_interface_version` (in Nightly builds, run with -Z macro-backtrace for more info)
help: wrap the attribute in `unsafe(...)`
  --> /home/fogti/.cargo/git/checkouts/uhyve-da4e7b3a9c9e3da7/d74257a/uhyve-interface/src/elf.rs:11:5
   |
11 |         #[unsafe(link_section = ".note.hermit.uhyve-interface-version")]
   |           +++++++                                                     +

error: could not compile `hermit-kernel` (lib) due to 1 previous error
```