fix(docs): don't enable removed doc_auto_cfg on docs.rs
```
[INFO] [stderr]  Documenting hermit-entry v0.10.5 (/opt/rustwide/workdir)
[INFO] [stderr] error[E0557]: feature has been removed
[INFO] [stderr]  --> src/lib.rs:8:38
[INFO] [stderr]   |
[INFO] [stderr] 8 | #![cfg_attr(docsrs, feature(doc_cfg, doc_auto_cfg))]
[INFO] [stderr]   |                                      ^^^^^^^^^^^^ feature has been removed
[INFO] [stderr]   |
[INFO] [stderr]   = note: removed in CURRENT_RUSTC_VERSION; see <https://github.com/rust-lang/rust/pull/138907> for more information
[INFO] [stderr]   = note: merged into `doc_cfg`
[INFO] [stderr]
[INFO] [stderr] error: Compilation failed, aborting rustdoc
[INFO] [stderr]
[INFO] [stderr] For more information about this error, try `rustc --explain E0557`.
[INFO] [stderr] error: could not document `hermit-entry`
```